In [2]:
import pandas as pd
from epw import epw
import dec

In [4]:
meteo=pd.read_csv('IGENVEVE2_from_2019-01-01_to_2019-12-31.csv',index_col='Date_Time',parse_dates=[0,])
meteo.head()

,Temperature_C,Dew_Point_C,Humidity,Wind,Speed_m/s,Gust_m/s,Pressure_Pa,Precip_Rate_mm,Precip_Accum_mm,UV,Solar_W/m2
Date_Time,,,,,,,,,,,
2019-01-01 00:00:00,4.277778,3.388889,94.0,45.0,0.0,0.894055,103442.3,0.0,0.0,0,0.0
2019-01-01 00:05:00,4.333333,3.444444,94.0,0.0,0.0,0.000000,103442.3,0.0,0.0,0,0.0
2019-01-01 00:10:00,4.388889,3.500000,94.0,0.0,0.0,0.000000,103442.3,0.0,0.0,0,0.0
2019-01-01 00:15:00,4.500000,3.611111,94.0,0.0,0.0,0.000000,103442.3,0.0,0.0,0,0.0
2019-01-01 00:20:00,4.555556,3.666667,94.0,45.0,0.0,2.235136,103442.3,0.0,0.0,0,0.0

In [6]:
meteo=meteo.resample('H').mean().interpolate()
meteo.head()

,Temperature_C,Dew_Point_C,Humidity,Wind,Speed_m/s,Gust_m/s,Pressure_Pa,Precip_Rate_mm,Precip_Accum_mm,UV,Solar_W/m2
Date_Time,,,,,,,,,,,
2019-01-01 00:00:00,5.162037,4.328704,94.333333,35.625,1.303830,2.905677,103442.300000,0.0,0.0,0.0,0.0
2019-01-01 01:00:00,6.453704,5.495370,93.583333,52.500,1.974370,4.135002,103442.300000,0.0,0.0,0.0,0.0
2019-01-01 02:00:00,6.337963,5.199074,92.500000,37.500,0.484280,1.937118,103445.121667,0.0,0.0,0.0,0.0
2019-01-01 03:00:00,6.050926,4.828704,92.000000,16.875,0.558784,2.533155,103436.656667,0.0,0.0,0.0,0.0
2019-01-01 04:00:00,6.092593,4.805556,91.416667,35.625,0.856802,2.719416,103380.223333,0.0,0.0,0.0,0.0

In [7]:
meteo.columns

Index(['Temperature_C', 'Dew_Point_C', 'Humidity', 'Wind', 'Speed_m/s',
       'Gust_m/s', 'Pressure_Pa', 'Precip_Rate_mm', 'Precip_Accum_mm', 'UV',
       'Solar_W/m2'],
      dtype='object')

In [8]:
latitude = 46.25  # latitude  N
longitude = 6.13  # longitude E
elevation = 416   # meters above the sea

In [13]:
data=epw()
data.read('CHE_Geneva_to_customize.067000_IWEC.epw')

In [14]:
head=data.headers # this is a dictionary of the header information
print(head)

{'LOCATION': ['GENEVA', '-', 'CHE', 'IWEC Data', '067000', '46.25', '6.13', '1.0', '416.0'], 'DESIGN CONDITIONS': ['1', 'Climate Design Data 2009 ASHRAE Handbook', '', 'Heating', '1', '-6.9', '-4.8', '-11', '1.5', '-4.8', '-9.1', '1.8', '-2.9', '11.3', '1.6', '9.5', '3.1', '2.3', '240', 'Cooling', '7', '11.5', '30.8', '19.3', '29', '18.8', '27.2', '18.3', '20.2', '27.9', '19.6', '26.9', '18.9', '25.7', '3.4', '230', '17.8', '13.4', '22.7', '17.1', '12.8', '21.9', '16.3', '12.2', '21.5', '60', '28.1', '57.6', '27', '55.2', '25.7', '959', 'Extremes', '9', '7.7', '6.6', '23.1', '-9.2', '33.6', '3', '1.7', '-11.3', '34.9', '-13.1', '35.8', '-14.8', '36.8', '-17', '38'], 'TYPICAL/EXTREME PERIODS': ['6', 'Summer - Week Nearest Max Temperature For Period', 'Extreme', '7/ 6', '7/12', 'Summer - Week Nearest Average Temperature For Period', 'Typical', '7/20', '7/26', 'Winter - Week Nearest Min Temperature For Period', 'Extreme', '1/ 6', '1/12', 'Winter - Week Nearest Average Temperature For Period', 'Typical', '12/ 8', '12/14', 'Autumn - Week Nearest Average Temperature For Period', 'Typical', '10/20', '10/26', 'Spring - Week Nearest Average Temperature For Period', 'Typical', '4/12', '4/18'], 'GROUND TEMPERATURES': ['3', '.5', '', '', '', '2.79', '2.05', '3.37', '5.43', '10.84', '15.02', '17.83', '18.69', '17.23', '13.99', '9.66', '5.64', '2', '', '', '', '5.53', '4.20', '4.48', '5.57', '9.19', '12.46', '15.08', '16.49', '16.19', '14.35', '11.37', '8.20', '4', '', '', '', '7.80', '6.44', '6.14', '6.55', '8.60', '10.81', '12.83', '14.23', '14.56', '13.77', '12.01', '9.87'], 'HOLIDAYS/DAYLIGHT SAVINGS': ['No', '0', '0', '0'], 'COMMENTS 1': ["IWEC- WMO#067000 - Europe -- Original Source Data (c) 2001 American Society of Heating, Refrigerating and Air-Conditioning Engineers (ASHRAE), Inc., Atlanta, GA, USA.  www.ashrae.org  All rights reserved as noted in the License Agreement and Additional Conditions. DISCLAIMER OF WARRANTIES: The data is provided 'as is' without warranty of any kind, either expressed or implied. The entire risk as to the quality and performance of the data is with you. In no event will ASHRAE or its contractors be liable to you for any damages, including without limitation any lost profits, lost savings, or other incidental or consequential damages arising out of the use or inability to use this data."], 'COMMENTS 2': [' -- Ground temps produced with a standard soil diffusivity of 2.3225760E-03 {m**2/day}'], 'DATA PERIODS': ['1', '1', 'Data', 'Sunday', ' 1/ 1', '12/31']}

In [15]:
df=data.dataframe.copy()  # this is pandas dataframe
df.columns

Index(['Year', 'Month', 'Day', 'Hour', 'Minute',
       'Data Source and Uncertainty Flags', 'Dry Bulb Temperature',
       'Dew Point Temperature', 'Relative Humidity',
       'Atmospheric Station Pressure', 'Extraterrestrial Horizontal Radiation',
       'Extraterrestrial Direct Normal Radiation',
       'Horizontal Infrared Radiation Intensity',
       'Global Horizontal Radiation', 'Direct Normal Radiation',
       'Diffuse Horizontal Radiation', 'Global Horizontal Illuminance',
       'Direct Normal Illuminance', 'Diffuse Horizontal Illuminance',
       'Zenith Luminance', 'Wind Direction', 'Wind Speed', 'Total Sky Cover',
       'Opaque Sky Cover (used if Horizontal IR Intensity missing)',
       'Visibility', 'Ceiling Height', 'Present Weather Observation',
       'Present Weather Codes', 'Precipitable Water', 'Aerosol Optical Depth',
       'Snow Depth', 'Days Since Last Snowfall', 'Albedo',
       'Liquid Precipitation Depth', 'Liquid Precipitation Quantity'],
      dtype='object')

In [17]:
df['Dry Bulb Temperature']=meteo.Temperature_C.values
df['Dew Point Temperature']=meteo.Dew_Point_C.values
df['Atmospheric Station Pressure'].unique()

array([98100, 98000, 97900, 97800, 97700, 97600, 97500, 97400, 97300,
       97200, 97100, 97000, 96900, 96800, 96700, 96600, 96500, 96400,
       96300, 96200, 96100, 96000, 95900, 95800, 95700, 95500, 95300,
       95100, 94900, 94700, 94500, 94400, 94300, 94200, 94800, 95000,
       95200, 95400, 95600, 98200, 98300, 98400, 98500, 98600])

In [18]:
meteo.Pressure_Pa.unique()

array([103442.3       , 103445.12166667, 103436.65666667, ...,
       103478.98166667, 103464.87333333, 103481.80333333])

In [19]:
df['Atmospheric Station Pressure']=meteo.Pressure_Pa.values
df['Relative Humidity']=meteo.Humidity.values
df['Wind Direction']=meteo.Wind.values
df['Wind Speed']=meteo['Speed_m/s'].values*3.6  #KMH

In [20]:
df.head()

,Year,Month,Day,Hour,Minute,Data Source and Uncertainty Flags,Dry Bulb Temperature,Dew Point Temperature,Relative Humidity,Atmospheric Station Pressure,...,Ceiling Height,Present Weather Observation,Present Weather Codes,Precipitable Water,Aerosol Optical Depth,Snow Depth,Days Since Last Snowfall,Albedo,Liquid Precipitation Depth,Liquid Precipitation Quantity
0,1984,1,1,1,60,C9C9C9C9*0?9?9?9?9?9?9?9A7A7A7A7A7A7*0E8*0*0,5.162037,4.328704,94.333333,103442.300000,...,22000,0,999999099,0,0.098,0,88,0.0,0.0,0.0
1,1984,1,1,2,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,6.453704,5.495370,93.583333,103442.300000,...,22000,9,999999999,0,0.098,0,88,0.0,0.0,0.0
2,1984,1,1,3,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,6.337963,5.199074,92.500000,103445.121667,...,22000,9,999999999,0,0.098,0,88,0.0,0.0,0.0
3,1984,1,1,4,60,C9C9C9C9*0?9?9?9?9?9?9?9A7A7A7A7A7A7*0E8*0*0,6.050926,4.828704,92.000000,103436.656667,...,22000,0,999999099,0,0.098,0,88,0.0,0.0,0.0
4,1984,1,1,5,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,6.092593,4.805556,91.416667,103380.223333,...,22000,9,999999999,0,0.098,0,88,0.0,0.0,0.0

In [21]:
data.dataframe.head()

,Year,Month,Day,Hour,Minute,Data Source and Uncertainty Flags,Dry Bulb Temperature,Dew Point Temperature,Relative Humidity,Atmospheric Station Pressure,...,Ceiling Height,Present Weather Observation,Present Weather Codes,Precipitable Water,Aerosol Optical Depth,Snow Depth,Days Since Last Snowfall,Albedo,Liquid Precipitation Depth,Liquid Precipitation Quantity
0,1984,1,1,1,60,C9C9C9C9*0?9?9?9?9?9?9?9A7A7A7A7A7A7*0E8*0*0,-2.4,-4.9,81,98100,...,22000,0,999999099,0,0.098,0,88,0.0,0.0,0.0
1,1984,1,1,2,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-1.8,-3.7,85,98100,...,22000,9,999999999,0,0.098,0,88,0.0,0.0,0.0
2,1984,1,1,3,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-1.4,-2.9,88,98100,...,22000,9,999999999,0,0.098,0,88,0.0,0.0,0.0
3,1984,1,1,4,60,C9C9C9C9*0?9?9?9?9?9?9?9A7A7A7A7A7A7*0E8*0*0,-1.4,-2.6,90,98100,...,22000,0,999999099,0,0.098,0,88,0.0,0.0,0.0
4,1984,1,1,5,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,-1.5,-2.6,91,98100,...,22000,9,999999999,0,0.098,0,88,0.0,0.0,0.0

In [22]:
data.dataframe=df.copy()

In [23]:
data.headers['LOCATION']

['GENEVA', '-', 'CHE', 'IWEC Data', '067000', '46.25', '6.13', '1.0', '416.0']

In [24]:
data.write('custom_epw_file.epw')

In [25]:
data.dataframe

,Year,Month,Day,Hour,Minute,Data Source and Uncertainty Flags,Dry Bulb Temperature,Dew Point Temperature,Relative Humidity,Atmospheric Station Pressure,...,Ceiling Height,Present Weather Observation,Present Weather Codes,Precipitable Water,Aerosol Optical Depth,Snow Depth,Days Since Last Snowfall,Albedo,Liquid Precipitation Depth,Liquid Precipitation Quantity
0,1984,1,1,1,60,C9C9C9C9*0?9?9?9?9?9?9?9A7A7A7A7A7A7*0E8*0*0,5.162037,4.328704,94.333333,103442.300000,...,22000,0,999999099,0,0.098,0,88,0.0,0.0,0.0
1,1984,1,1,2,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,6.453704,5.495370,93.583333,103442.300000,...,22000,9,999999999,0,0.098,0,88,0.0,0.0,0.0
2,1984,1,1,3,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,6.337963,5.199074,92.500000,103445.121667,...,22000,9,999999999,0,0.098,0,88,0.0,0.0,0.0
3,1984,1,1,4,60,C9C9C9C9*0?9?9?9?9?9?9?9A7A7A7A7A7A7*0E8*0*0,6.050926,4.828704,92.000000,103436.656667,...,22000,0,999999099,0,0.098,0,88,0.0,0.0,0.0
4,1984,1,1,5,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,6.092593,4.805556,91.416667,103380.223333,...,22000,9,999999999,0,0.098,0,88,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,1984,12,31,20,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,2.199074,1.310185,94.000000,103510.020000,...,22000,9,999999999,0,0.068,0,88,0.0,0.0,0.0
8756,1984,12,31,21,60,C9C9C9C9*0?9?9?9?9?9?9?9A7A7B8B8A7A7*0E8*0*0,2.277778,1.388889,94.000000,103510.020000,...,22000,9,999999999,0,0.068,0,88,0.0,0.0,0.0
8757,1984,12,31,22,60,C9C9C9C9*0?9?9?9?9?9?9?9A7A7B8B8B8*0*0E8*0*0,2.365741,1.476852,94.000000,103487.446667,...,22000,9,999999999,0,0.068,0,88,0.0,0.0,0.0
8758,1984,12,31,23,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,2.550926,1.662037,94.000000,103476.160000,...,22000,9,999999999,0,0.068,0,88,0.0,0.0,0.0
8759,1984,12,31,24,60,C9C9C9C9*0?9?9?9?9?9?9?9*0B8B8B8B8*0*0E8*0*0,2.351852,1.462963,94.000000,103481.803333,...,22000,9,999999999,0,0.068,0,88,0.0,0.0,0.0